name: Unit Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      SENDER_NAME: ${{ secrets.SENDER_NAME }}
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with: 
        node-version: '14'
        cache: "npm"
    - run: npm ci
    - name: Run unit test
      run: npm test